# Setup
title:               A po-Data Science project
tagline:             'BST 260 project webpage'
description:         'A reserved <a href="https://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://Po-Data-Science-Project.github.io
baseurl:             'Po-Data-Science-Project'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Han Choi, Yeeun Lee, Amy Luo, Juliet McCann, Austin Tucker
  url:               https://twitter.com/amyyyyluo
  email:             amyluo@hsph.harvard.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
